from django.conf import settings
from django.urls import path

from .views import (
    # 真实业务视图
    AuthCallbackView,
    CaptchaChallengeView,
    AuthLoginView,
    AuthRefreshView,
    AuthMeView,
    MobileAuthLoginView,
    UserAccountDeleteView,
    PhoneRebindAppealCreateView,
    SmsChannelStatsView,
    SmsCodeSendView,
    SmsCodeVerifyView,
    UserLoginView,
    UserRegisterView,
    UserRegisterSubmitView,
    UserRegisterStatusView,
    UserTokenRefreshView,
    # 采集 & 同步
    CollectionTaskCreateView,
    CollectionTaskStatusView,
    Collect1688SingleView,
    BatchScrapeView,
    CollectExportView,
    ScrapeRulesView,
    PageProxyView,
    SyncTriggerView,
    SyncLogView,
    # 商品
    GoodsDetailView,
    GoodsListCreateView,
    GoodsListingView,
    GoodsBatchListingView,
    # 库存
    InventoryAlertsView,
    InventoryLogsView,
    InventorySyncView,
    InventoryOverviewView,
    InventoryAdjustView,
    WarehouseListView,
    # 订单
    OrdersExportView,
    OrdersListView,
    OrdersStatsView,
    OrdersDetailView,
    OrderActionView,
    OrderAddressUpdateView,
    OrderStatusUpdateView,
    OrderRemarkView,
    # 物流
    LogisticsShipmentsView,
    LogisticsTrackView,
    LogisticsWebhookView,
    LogisticsCarriersView,
    LogisticsSyncView,
    LogisticsSubscribeView,
    FreightEstimateView,
    # Dashboard & 报表
    DashboardSalesTrendView,
    DashboardRecentOrdersView,
    DashboardStatsView,
    DashboardNewOrdersSinceView,
    ReportsSummaryView,
    # 店铺
    ShopListView,
    ShopUnbindView,
    # 运维
    HealthCheckView,
    DeadLetterListView,
    DeadLetterReplayView,
    ReplayAuditLogListView,
    OpsWhoAmIView,
    # 图片上传
    ImageUploadView,
    # AI
    AiProxyView,
    AiGenerateTitleView,
    AiGenerateDescriptionView,
    AiGenerateFeaturesView,
    AiChatView,
    AiImageGenerateView,
    AiImageEditView,
    AiTranslateView,
    AiRefineDescriptionView,
    # Demo视图（DEMO_MODE=true时使用）
    DemoAuthLoginView,
    DemoAuthMeView,
    DemoAuthRefreshView,
    DemoAuthRegisterView,
    DemoGoodsListView,
    DemoGoodsDetailView,
    DemoGoodsListingSyncView,
    DemoGoodsBatchListingSyncView,
    DemoAuthSendSmsView,
    DemoAuthVerifySmsView,
    DemoSmsQueryView,
    DemoCollectAuthView,
    DemoCollectTaskView,
    DemoAiExtendedView,
    DemoOrdersView,
    DemoOrdersStatsView,
    DemoInventoryView,
    DemoLogisticsView,
    DemoCollect1688SingleView,
    DemoCollect1688BatchView,
    DemoAiGenerateTitleView,
    DemoAiGenerateDescriptionView,
    DemoAiGenerateFeaturesView,
)

_common_urls = [
    path("auth/captcha/challenge", CaptchaChallengeView.as_view(), name="auth-captcha-challenge"),
    path("auth/sms/send-code", SmsCodeSendView.as_view(), name="auth-sms-send-code"),
    path("auth/sms/verify-code", SmsCodeVerifyView.as_view(), name="auth-sms-verify-code"),
    path("auth/mobile/login", MobileAuthLoginView.as_view(), name="auth-mobile-login"),
    path("user/account/", UserAccountDeleteView.as_view(), name="user-account-delete"),
    path("user/phone-rebind-appeals", PhoneRebindAppealCreateView.as_view(), name="user-phone-rebind-appeals"),
    path("ops/sms/channel-stats", SmsChannelStatsView.as_view(), name="ops-sms-channel-stats"),
    path("auth/<str:platform>/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/<str:platform>/callback/", AuthCallbackView.as_view(), name="auth-callback"),
    path("auth/<str:platform>/refresh/", AuthRefreshView.as_view(), name="auth-refresh"),
    path("goods/", GoodsListCreateView.as_view(), name="goods-list-create"),
    path("goods/<int:goods_id>", GoodsDetailView.as_view(), name="goods-detail"),
    path("shops/", ShopListView.as_view(), name="shops-list"),
    path("inventory/alerts", InventoryAlertsView.as_view(), name="inventory-alerts"),
    path("inventory/logs", InventoryLogsView.as_view(), name="inventory-logs"),
    path("inventory/sync", InventorySyncView.as_view(), name="inventory-sync"),
    path("orders/", OrdersListView.as_view(), name="orders-list"),
    path("orders/status-counts/", OrdersStatsView.as_view(), name="orders-status-counts"),
    path("orders/export", OrdersExportView.as_view(), name="orders-export"),
    path("orders/<int:order_id>/", OrdersDetailView.as_view(), name="orders-detail"),
    path("orders/<int:order_id>/address", OrderAddressUpdateView.as_view(), name="orders-address-update"),
    path("orders/<int:order_id>/status", OrderStatusUpdateView.as_view(), name="orders-status-update"),
    path("orders/<int:order_id>/confirm/", OrderActionView.as_view(), name="orders-confirm"),
    path("orders/<int:order_id>/ship/", OrderActionView.as_view(), name="orders-ship"),
    path("orders/<int:order_id>/cancel/", OrderActionView.as_view(), name="orders-cancel"),
    path("orders/<int:order_id>/remark/", OrderRemarkView.as_view(), name="orders-remark"),
    path("dashboard/stats", DashboardStatsView.as_view(), name="dashboard-stats"),
    path("dashboard/recent-orders", DashboardRecentOrdersView.as_view(), name="dashboard-recent-orders"),
    path("dashboard/sales-trend", DashboardSalesTrendView.as_view(), name="dashboard-sales-trend"),
    path("dashboard/new-orders-since", DashboardNewOrdersSinceView.as_view(), name="dashboard-new-orders-since"),
    path("reports/summary/", ReportsSummaryView.as_view(), name="reports-summary"),
    path("inventory/overview", InventoryOverviewView.as_view(), name="inventory-overview"),
    path("inventory/adjust", InventoryAdjustView.as_view(), name="inventory-adjust"),
    path("inventory/warehouses", WarehouseListView.as_view(), name="inventory-warehouses"),
    path("shops/unbind/", ShopUnbindView.as_view(), name="shops-unbind"),
    path("logistics/carriers/", LogisticsCarriersView.as_view(), name="logistics-carriers"),
    path("logistics/sync/", LogisticsSyncView.as_view(), name="logistics-sync"),
    path("logistics/subscribe/", LogisticsSubscribeView.as_view(), name="logistics-subscribe"),
    path("v1/upload/image/", ImageUploadView.as_view(), name="upload-image"),
    path("v1/goods/listing/", GoodsListingView.as_view(), name="goods-listing"),
    path("v1/goods/listing/batch/", GoodsBatchListingView.as_view(), name="goods-listing-batch"),
    path("v1/collect/1688/single/", Collect1688SingleView.as_view(), name="collect-1688-single"),
    path("v1/collect/batch/scrape/", BatchScrapeView.as_view(), name="collect-batch-scrape"),
    path("v1/collect/export/", CollectExportView.as_view(), name="collect-export"),
    path("v1/collect/rules/", ScrapeRulesView.as_view(), name="collect-rules"),
    path("v1/proxy/page/", PageProxyView.as_view(), name="proxy-page"),
    path("logistics/shipments/", LogisticsShipmentsView.as_view(), name="logistics-shipments"),
    path("logistics/track/<str:waybill>", LogisticsTrackView.as_view(), name="logistics-track"),
    path("logistics/webhook", LogisticsWebhookView.as_view(), name="logistics-webhook"),
    path("logistics/freight-estimate", FreightEstimateView.as_view(), name="logistics-freight-estimate"),
    path("tasks/collect/", CollectionTaskCreateView.as_view(), name="task-collect"),
    path("tasks/<int:task_id>/status/", CollectionTaskStatusView.as_view(), name="task-status"),
    path("sync/trigger/", SyncTriggerView.as_view(), name="sync-trigger"),
    path("sync/log/", SyncLogView.as_view(), name="sync-log"),
    path("ops/dead-letter/", DeadLetterListView.as_view(), name="dead-letter-list"),
    path("ops/dead-letter/<int:dead_letter_id>/replay/", DeadLetterReplayView.as_view(), name="dead-letter-replay"),
    path("ops/replay-audit/", ReplayAuditLogListView.as_view(), name="replay-audit-list"),
    path("ops/whoami/", OpsWhoAmIView.as_view(), name="ops-whoami"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
    # AI 功能（真实拓岳AI）
    path("ai/proxy", AiProxyView.as_view(), name="ai-proxy"),
    path("ai/generate-title/", AiGenerateTitleView.as_view(), name="ai-generate-title"),
    path("ai/generate-description/", AiGenerateDescriptionView.as_view(), name="ai-generate-description"),
    path("ai/generate-features/", AiGenerateFeaturesView.as_view(), name="ai-generate-features"),
    path("ai/chat/", AiChatView.as_view(), name="ai-chat"),
    path("ai/image/generate/", AiImageGenerateView.as_view(), name="ai-image-generate"),
    path("ai/image/edit/", AiImageEditView.as_view(), name="ai-image-edit"),
    path("ai/translate/", AiTranslateView.as_view(), name="ai-translate"),
    path("ai/refine-description/", AiRefineDescriptionView.as_view(), name="ai-refine-description"),
]

demo_urls = [
    path("auth/login", DemoAuthLoginView.as_view(), name="demo-auth-login"),
    path("auth/me", DemoAuthMeView.as_view(), name="demo-auth-me"),
    path("auth/refresh", DemoAuthRefreshView.as_view(), name="demo-auth-refresh"),
    path("auth/register", DemoAuthRegisterView.as_view(), name="demo-auth-register"),
    path("auth/register/", DemoAuthRegisterView.as_view(), name="demo-auth-register-slash"),
    path("auth/send-sms", DemoAuthSendSmsView.as_view(), name="demo-auth-send-sms"),
    path("auth/verify-sms", DemoAuthVerifySmsView.as_view(), name="demo-auth-verify-sms"),
    path("sms/send/", DemoAuthSendSmsView.as_view(), name="demo-sms-send"),
    path("sms/verify/", DemoAuthVerifySmsView.as_view(), name="demo-sms-verify"),
    path("sms/query/", DemoSmsQueryView.as_view(), name="demo-sms-query"),
    path("sms/send-batch/", DemoAuthSendSmsView.as_view(), name="demo-sms-send-batch"),
    path("v1/goods/list", DemoGoodsListView.as_view(), name="demo-goods-list"),
    path("v1/goods/detail/<int:goods_id>/", DemoGoodsDetailView.as_view(), name="demo-goods-detail"),
    path("v1/products/", DemoGoodsListView.as_view(), name="demo-products-list"),
    path("v1/goods/listing/", DemoGoodsListingSyncView.as_view(), name="demo-goods-listing-sync"),
    path("v1/goods/listing/batch/", DemoGoodsBatchListingSyncView.as_view(), name="demo-goods-listing-batch-sync"),
    path("v1/orders/", DemoOrdersView.as_view(), name="demo-orders-list"),
    path("v1/orders/stats/", DemoOrdersStatsView.as_view(), name="demo-orders-stats"),
    path("v1/orders/<int:order_id>/", DemoOrdersView.as_view(), name="demo-orders-detail"),
    path("v1/orders/<int:order_id>/<str:action>/", DemoOrdersView.as_view(), name="demo-orders-action"),
    path("v1/collect/1688/single/", DemoCollect1688SingleView.as_view(), name="demo-collect-1688-single"),
    path("v1/collect/1688/batch/", DemoCollect1688BatchView.as_view(), name="demo-collect-1688-batch"),
    path("v1/collect/<str:platform>/auth/login/", DemoCollectAuthView.as_view(), name="demo-collect-auth-login"),
    path("v1/collect/<str:platform>/auth/callback/", DemoCollectAuthView.as_view(), name="demo-collect-auth-callback"),
    path("v1/collect/<str:platform>/auth/status/", DemoCollectAuthView.as_view(), name="demo-collect-auth-status"),
    path("v1/collect/<str:platform>/auth/logout/", DemoCollectAuthView.as_view(), name="demo-collect-auth-logout"),
    path("v1/collect/task/", DemoCollectTaskView.as_view(), name="demo-collect-task-create"),
    path("v1/collect/task/list/", DemoCollectTaskView.as_view(), name="demo-collect-task-list"),
    path("v1/collect/task/<int:task_id>/", DemoCollectTaskView.as_view(), name="demo-collect-task-detail"),
    path("v1/collect/task/<int:task_id>/status/", DemoCollectTaskView.as_view(), name="demo-collect-task-status"),
    path("v1/collect/task/<int:task_id>/cancel/", DemoCollectTaskView.as_view(), name="demo-collect-task-cancel"),
    path("v1/inventory/list/", DemoInventoryView.as_view(), name="demo-inventory-list"),
    path("v1/inventory/alerts/", DemoInventoryView.as_view(), name="demo-inventory-alerts"),
    path("v1/inventory/sku/<str:sku>/", DemoInventoryView.as_view(), name="demo-inventory-sku"),
    path("v1/inventory/adjust/", DemoInventoryView.as_view(), name="demo-inventory-adjust"),
    path("v1/inventory/logs/", DemoInventoryView.as_view(), name="demo-inventory-logs"),
    path("v1/inventory/overview/", DemoInventoryView.as_view(), name="demo-inventory-overview"),
    path("v1/inventory/warehouses/", DemoInventoryView.as_view(), name="demo-inventory-warehouses"),
    path("v1/inventory/sync/trigger/", DemoInventoryView.as_view(), name="demo-inventory-sync-trigger"),
    path("v1/inventory/sync/log/", DemoInventoryView.as_view(), name="demo-inventory-sync-log"),
    path("v1/logistics/shipments/", DemoLogisticsView.as_view(), name="demo-logistics-shipments"),
    path("v1/logistics/stats/", DemoLogisticsView.as_view(), name="demo-logistics-stats"),
    path("v1/logistics/track/<str:waybill>/", DemoLogisticsView.as_view(), name="demo-logistics-track"),
    path("v1/logistics/sync/", DemoLogisticsView.as_view(), name="demo-logistics-sync"),
    path("v1/logistics/carriers/", DemoLogisticsView.as_view(), name="demo-logistics-carriers"),
    path("v1/logistics/subscribe/", DemoLogisticsView.as_view(), name="demo-logistics-subscribe"),
    path("ai/proxy", AiProxyView.as_view(), name="ai-proxy"),
    path("ai/generate-title/", DemoAiGenerateTitleView.as_view(), name="demo-ai-generate-title"),
    path("ai/generate-description/", DemoAiGenerateDescriptionView.as_view(), name="demo-ai-generate-description"),
    path("ai/generate-features/", DemoAiGenerateFeaturesView.as_view(), name="demo-ai-generate-features"),
    path("ai/chat/", DemoAiExtendedView.as_view(), name="demo-ai-chat"),
    path("ai/image/generate/", DemoAiExtendedView.as_view(), name="demo-ai-image-generate"),
    path("ai/image/edit/", DemoAiExtendedView.as_view(), name="demo-ai-image-edit"),
    path("ai/translate/", DemoAiExtendedView.as_view(), name="demo-ai-translate"),
    path("ai/refine-description/", DemoAiExtendedView.as_view(), name="demo-ai-refine-description"),
]

_business_auth_urls = [
    path("auth/register", UserRegisterView.as_view(), name="auth-register"),
    path("auth/register/", UserRegisterView.as_view(), name="auth-register-slash"),
    path("auth/register-submit/", UserRegisterSubmitView.as_view(), name="auth-register-submit"),
    path("auth/register-status/", UserRegisterStatusView.as_view(), name="auth-register-status"),
    path("auth/login", UserLoginView.as_view(), name="auth-login-user"),
    path("auth/refresh", UserTokenRefreshView.as_view(), name="auth-refresh-user"),
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    # 前端固定路径兼容到真实短信验证码接口
    path("auth/send-sms", SmsCodeSendView.as_view(), name="auth-send-sms-compat"),
    path("auth/verify-sms", SmsCodeVerifyView.as_view(), name="auth-verify-sms-compat"),
]

urlpatterns = (_demo_urls if getattr(settings, "DEMO_MODE", False) else _business_auth_urls) + _common_urls
