/**
 * 采集注入脚本 —— 注入到货源平台 iframe 中
 * 识别商品卡片 + 拖拽提取数据 + postMessage 回传
 */
export function getCollectScript(platformKey) {
  // 拼接为纯字符串，避免 Vue SFC 编译器误解析模板字面量
  return [
    '(function() {',
    '  if (window.__erpCollectInjected__) return;',
    '  window.__erpCollectInjected__ = true;',
    '',
    '  var selectedEl = null;',
    '',
    '  document.addEventListener("mouseup", function(e) {',
    '    var el = e.target;',
    '    for (var i = 0; i < 5; i++) {',
    '      if (!el) break;',
    '      var matches = el.matches;',
    '      if (matches && (',
    '        matches.call(el, "[data-id]") ||',
    '        matches.call(el, ".offer-item") ||',
    '        matches.call(el, ".item") ||',
    '        matches.call(el, ".product-item") ||',
    '        matches.call(el, "[class*=\\"offer\\"]") ||',
    '        matches.call(el, "[class*=\\"product\\"]") ||',
    '        matches.call(el, "[class*=\\"item\\"]")',
    '      )) {',
    '        selectedEl = el;',
    '        break;',
    '      }',
    '      el = el.parentElement;',
    '    }',
    '  });',
    '',
    '  document.addEventListener("dragstart", function(e) {',
    '    if (!selectedEl) return;',
    '    var data = extractProductData(selectedEl);',
    '    if (data) {',
    '      window.parent.postMessage({',
    '        type: "ONESTOP_COLLECT_PRODUCT",',
    '        product: data,',
    '      }, "*");',
    '    }',
    '  }, true);',
    '',
    '  function extractProductData(el) {',
    '    try {',
    '      function getText(sel) {',
    '        var n = el.querySelector(sel);',
    '        return n ? (n.innerText || "").trim() : "";',
    '      }',
    '',
    '      var title = getText("h2") || getText(".title") ||',
    '        getText("[class*=\\"title\\"]") ||',
    '        (el.querySelector("a") || {}).href || document.title;',
    '',
    '      var priceText = getText("[class*=\\"price\\"]") || getText(".price");',
    '      var price = parseFloat((priceText || "").replace(/[^0-9.]/g, "")) || 0;',
    '',
    '      var imgEl = el.querySelector("img");',
    '      var image = (imgEl || {}).src || "";',
    '',
    '      var link = (el.querySelector("a") || {}).href || "";',
    '',
    '      if (title || price || image) {',
    '        return {',
    '          name: title, title: title, price: price,',
    '          images: image ? [image] : [], sourceUrl: link,',
    '          platform: "1688", _source: "iframeInject",',
    '          _timestamp: Date.now(),',
    '        };',
    '      }',
    '    } catch (err) {',
    '      console.error("[ERP Collect] extract fail:", err);',
    '    }',
    '    return null;',
    '  }',
    '',
    '  window.parent.postMessage({',
    '    type: "ONESTOP_SCRIPT_READY",',
    '    platformKey: "' + (platformKey || '') + '",',
    '  }, "*");',
    '})()',
  ].join('\n')
}
