# Generated by Django 6.0.4 on 2026-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_logist_carrier_4b834f_idx_core_logist_carrier_a3ffd5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok Shop'), ('amazon', 'Amazon'), ('1688', '1688')], db_index=True, max_length=20)),
                ('field_name', models.CharField(help_text='字段名: title/price/image/spec/stock', max_length=64)),
                ('css_selector', models.CharField(blank=True, default='', max_length=255)),
                ('regex_pattern', models.CharField(blank=True, default='', max_length=500)),
                ('image_attr', models.CharField(blank=True, default='src', max_length=32)),
                ('data_script_regex', models.CharField(blank=True, default='', help_text='从 <script> 提取 JSON 的正则', max_length=500)),
                ('priority', models.IntegerField(default=0, help_text='优先级，数字越大越优先')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('platform', '-priority'),
            },
        ),
    ]
