# Generated by Django 6.0.4 on 2026-05-02 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scraperule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('user_type', models.CharField(default='personal', max_length=20)),
                ('real_name', models.CharField(blank=True, default='', max_length=64)),
                ('id_card', models.CharField(blank=True, default='', max_length=18)),
                ('company_name', models.CharField(blank=True, default='', max_length=128)),
                ('credit_code', models.CharField(blank=True, default='', max_length=32)),
                ('legal_person', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('experience', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
